--------------------------------------------------------
--  File created - Íåäåëÿ-Ìàðò-15-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEASURES
--------------------------------------------------------

  CREATE TABLE "GABY"."MEASURES" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "GABY"."PRODUCTS" 
   (	"ID" NUMBER(*,0), 
	"VENDOR_ID" NUMBER(*,0), 
	"PRODUCT_NAME" VARCHAR2(50 BYTE), 
	"MEASURE_ID" NUMBER(*,0), 
	"PRICE" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VENDORS
--------------------------------------------------------

  CREATE TABLE "GABY"."VENDORS" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GABY.MEASURES
SET DEFINE OFF;
Insert into GABY.MEASURES (ID,NAME) values (1,'liters');
Insert into GABY.MEASURES (ID,NAME) values (2,'grams');
Insert into GABY.MEASURES (ID,NAME) values (3,'kilograms');
Insert into GABY.MEASURES (ID,NAME) values (4,'milliliters');
REM INSERTING into GABY.PRODUCTS
SET DEFINE OFF;
Insert into GABY.PRODUCTS (ID,VENDOR_ID,PRODUCT_NAME,MEASURE_ID,PRICE) values (1,2,'Beer “Zagorka',1,0.86);
Insert into GABY.PRODUCTS (ID,VENDOR_ID,PRODUCT_NAME,MEASURE_ID,PRICE) values (2,3,'Vodka “Targovishte',1,7.56);
Insert into GABY.PRODUCTS (ID,VENDOR_ID,PRODUCT_NAME,MEASURE_ID,PRICE) values (3,2,'Beer "Beck’s',1,1.03);
Insert into GABY.PRODUCTS (ID,VENDOR_ID,PRODUCT_NAME,MEASURE_ID,PRICE) values (4,1,'Chocolate "Milka"',2,2.8);
REM INSERTING into GABY.VENDORS
SET DEFINE OFF;
Insert into GABY.VENDORS (ID,NAME) values (1,'Nestle Sofia Corp.');
Insert into GABY.VENDORS (ID,NAME) values (2,'Zagorka Corp.');
Insert into GABY.VENDORS (ID,NAME) values (3,'Targovishte Bottling Company Ltd.');
Insert into GABY.VENDORS (ID,NAME) values (4,'Ivena Comers-GD');
Insert into GABY.VENDORS (ID,NAME) values (5,'Daris Honey Trading');
Insert into GABY.VENDORS (ID,NAME) values (6,'Max Medica');
Insert into GABY.VENDORS (ID,NAME) values (7,'Frut Corect');
Insert into GABY.VENDORS (ID,NAME) values (8,'Vantea');
Insert into GABY.VENDORS (ID,NAME) values (9,'Sams97');
Insert into GABY.VENDORS (ID,NAME) values (10,'RelexEp');
Insert into GABY.VENDORS (ID,NAME) values (11,'Avis');
Insert into GABY.VENDORS (ID,NAME) values (12,'AquaTrade');
Insert into GABY.VENDORS (ID,NAME) values (13,'Elixir');
Insert into GABY.VENDORS (ID,NAME) values (14,'E-bakalia');
Insert into GABY.VENDORS (ID,NAME) values (15,'Radex');
Insert into GABY.VENDORS (ID,NAME) values (16,'Dovex');
Insert into GABY.VENDORS (ID,NAME) values (17,'VSDrinks');
Insert into GABY.VENDORS (ID,NAME) values (18,'Toby Ltd.');
Insert into GABY.VENDORS (ID,NAME) values (19,'Brevis');
Insert into GABY.VENDORS (ID,NAME) values (20,'Seva Ltd.');
--------------------------------------------------------
--  DDL for Index VENDORS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GABY"."VENDORS_PK" ON "GABY"."VENDORS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GABY"."PRODUCTS_PK" ON "GABY"."PRODUCTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEASURES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GABY"."MEASURES_PK" ON "GABY"."MEASURES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEASURES
--------------------------------------------------------

  ALTER TABLE "GABY"."MEASURES" ADD CONSTRAINT "MEASURES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GABY"."MEASURES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "GABY"."MEASURES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VENDORS
--------------------------------------------------------

  ALTER TABLE "GABY"."VENDORS" ADD CONSTRAINT "VENDORS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GABY"."VENDORS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "GABY"."VENDORS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "GABY"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GABY"."PRODUCTS" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "GABY"."PRODUCTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "GABY"."PRODUCTS" ADD CONSTRAINT "FK_PRODUCTS_MEASURES_MEASUREID" FOREIGN KEY ("MEASURE_ID")
	  REFERENCES "GABY"."MEASURES" ("ID") ENABLE;
  ALTER TABLE "GABY"."PRODUCTS" ADD CONSTRAINT "FK_PRODUCTS_VENDORS_VENDORID" FOREIGN KEY ("VENDOR_ID")
	  REFERENCES "GABY"."VENDORS" ("ID") ENABLE;
