//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICES
    {
        public decimal SUPERMARKET_ID { get; set; }
        public decimal PRODUCT_ID { get; set; }
        public Nullable<decimal> PRICE_VALUE { get; set; }
    
        public virtual PRODUCTS PRODUCTS { get; set; }
        public virtual SUPERMARKETS SUPERMARKETS { get; set; }
    }
}
