//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsSystem.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductsSystemOracleEntities : DbContext
    {
        public ProductsSystemOracleEntities()
            : base("name=ProductsSystemOracleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Expenses> Expenses { get; set; }
        public virtual DbSet<MEASURES> MEASURES { get; set; }
        public virtual DbSet<PRICES> PRICES { get; set; }
        public virtual DbSet<PRODUCTS> PRODUCTS { get; set; }
        public virtual DbSet<SUPERMARKETS> SUPERMARKETS { get; set; }
        public virtual DbSet<VENDORS> VENDORS { get; set; }
    }
}
